
on:
  push:
    branches: [pipeline]
  pull_request:
    branches: [pipeline]
  schedule:
    - cron: '0 9, 11, 15, 18 * * 1,2,3,4,5'

  jobs:
  robot_test:
    runs-on: ubuntu-latest
    - name: Robot Framework
      uses: tarathep/robotframework-github-action@v1.0
      with:
        image: kietara/robot-framework
        image_version: 1.0
        tests_dir: '${{ github.workspace }}/tests/robot'
        reports_dir: '${{ github.workspace }}/tests/robot/reports';