name: Robot Framework CI

on:
  push:
    branches:
      - pipeline
  pull_request:
      - pipeline
  schedule:
    - cron: '0 9, 11, 15, 18 * * 1,2,3,4,5'

jobs:
    Run-Test:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - name: Install pip dependencies
          run: |
            pip install --upgrade pip
      


