name: Robot Framework CI

on:
  push:
    branches:
      - pipeline
  pull_request:
  workflow_dispatch:

jobs:
    Run-Test:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - name: Install pip dependencies
          run: |
            pip install --upgrade pip
        - name: Run Test
          run: python3 -m robot --outputdir results testes/MeusResultados
        - name: Run Test and create report
          run: python3 -m robot -d reports -x junit-report.xml "testes/MeusResultados"
