name: Run WEB Tests
run-name: On Push - WEB Tests Run 
on: [push]

jobs:
  web-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Install Python 3.10
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - run: |
          python -m install --upgrade pip

